nmct.ssa.cashlessproject.webapp.it/Controllers/ErrorlogController.cs
using nmct.ba.cashlessproject.model.Management;
using nmct.ssa.cashlessproject.webapp.it.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nmct.ssa.cashlessproject.webapp.it.Controllers
{
    [Authorize]
    public class ErrorlogController : Controller
    {
        // GET: Errorlog
        public ActionResult Index()
        {
            List<Errorlog> errorlogs = new List<Errorlog>();
            errorlogs = ErrorlogDA.GetErrorlogs();

            return View("Index", errorlogs);
        }
    }
}

nmct.ssa.cashlessproject.webapp.it/Controllers/KassaController.cs
using nmct.ba.cashlessproject.model.IT;
using nmct.ssa.cashlessproject.webapp.it.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nmct.ssa.cashlessproject.webapp.it.Controllers
{
    [Authorize]
    public class KassaController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            List<KassaIT> kassas = KassaDA.GetKassas();

            return View(kassas);
        }

        [HttpGet]
        public ActionResult New()
        {
            List<Organisatie> organisaties = OrganisatieDA.GetOrganisaties();

            Organisatie geenOrg = new Organisatie() { ID = 0, OrganisatieNaam = "geen organisatie" };
            organisaties.Insert(0, geenOrg);
            ViewBag.Organisaties = new SelectList(organisaties, "ID", "OrganisatieNaam");

            return PartialView("_New");
        }

        [HttpPost]
        public ActionResult New(KassaIT kassa)
        {
            kassa.ID = KassaDA.AddKassa(kassa);
            if (kassa.SelectedOrganisatieID != 0) OrganisatieKassaDA.AddOrganisatieKassa(kassa);
           
            return RedirectToAction("Index");

            //if (ModelState.IsValid) return RedirectToAction("Index");
            //else return PartialView("_New", organisatie);
        }


        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue) return RedirectToAction("Index");

            KassaIT kassa = KassaDA.GetKassaById(id.Value);

            List<Organisatie> organisaties = OrganisatieDA.GetOrganisaties();
            List<OrganisatieKassa> organisatiekassas = OrganisatieKassaDA.GetOrganisatieKassas();

            Organisatie geenOrg = new Organisatie() { ID = 0, OrganisatieNaam = "geen organisatie" };
            organisaties.Insert(0, geenOrg);

            OrganisatieKassa orgkassa = organisatiekassas.FirstOrDefault(ok => ok.KassaIT.ID == id.Value);
            if (orgkassa != null) kassa.SelectedOrganisatieID = orgkassa.Organisatie.ID;
            else kassa.SelectedOrganisatieID = geenOrg.ID;
            
            ViewBag.Organisaties = new SelectList(organisaties, "ID", "OrganisatieNaam", kassa.SelectedOrganisatieID);

            return PartialView("_Edit", kassa);
        }

        [HttpPost]
        public ActionResult Edit(KassaIT kassa)
        {
            KassaDA.UpdateKassa(kassa);

            List<OrganisatieKassa> organisatiekassas = OrganisatieKassaDA.GetOrganisatieKassas();
            OrganisatieKassa selectedorganisatiekassa = organisatiekassas.FirstOrDefault(ok => ok.KassaIT.ID == kassa.ID);

            if (selectedorganisatiekassa != null)
            {
                if (kassa.SelectedOrganisatieID == 0) OrganisatieKassaDA.DeleteOrganisatieKassa(kassa);
                else OrganisatieKassaDA.UpdateOrganisatieKassa(kassa);
            }
            else OrganisatieKassaDA.AddOrganisatieKassa(kassa);
            
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (!id.HasValue) return RedirectToAction("Index");

            KassaIT kassa = KassaDA.GetKassaById(id.Value);

            List<OrganisatieKassa> organisatiekassas = OrganisatieKassaDA.GetOrganisatieKassas();  
            OrganisatieKassa orgkassa = organisatiekassas.FirstOrDefault(ok => ok.KassaIT.ID == kassa.ID);

            if (orgkassa != null) ViewBag.SelectedOrganisatie = orgkassa.Organisatie.OrganisatieNaam;
            else ViewBag.SelectedOrganisatie = "geen organisatie";
           
            return PartialView("_Details", kassa);
        }

        [HttpGet]
        public ActionResult Delete(int? id)
        {
            if (!id.HasValue) return RedirectToAction("Index");

            KassaIT kassa = KassaDA.GetKassaById(id.Value);
            ViewBag.KassaNaam = kassa.KassaNaam;

            List<OrganisatieKassa> organisatiekassas = OrganisatieKassaDA.GetOrganisatieKassas();
            OrganisatieKassa orgkassa = organisatiekassas.FirstOrDefault(ok => ok.KassaIT.ID == kassa.ID);

            if (orgkassa != null) ViewBag.SelectedOrganisatie = orgkassa.Organisatie.OrganisatieNaam;
            else ViewBag.SelectedOrganisatie = "geen organisatie";

            return PartialView("_Delete", kassa);
        }


        [HttpPost]
        public ActionResult Delete(KassaIT kassa)
        {
            OrganisatieKassaDA.DeleteOrganisatieKassa(kassa);
            KassaDA.DeleteKassa(kassa);

            return RedirectToAction("Index");
        }
    }
}

nmct.ssa.cashlessproject.webapp.it/Controllers/OrganisatieController.cs
using nmct.ba.cashlessproject.model.IT;
using nmct.ssa.cashlessproject.webapp.it.DataAccess;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace nmct.ssa.cashlessproject.webapp.it.Controllers
{
    [Authorize]
    public class OrganisatieController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            List<Organisatie> organisaties = new List<Organisatie>();
            organisaties = OrganisatieDA.GetOrganisaties();

            return View("Index", organisaties);
        }


        [HttpGet]
        public ActionResult New()
        {
            return PartialView("_New");
        }

        [HttpPost]
        public ActionResult New(Organisatie organisatie)
        {
            OrganisatieDA.AddOrganisatie(organisatie);
            return RedirectToAction("Index");

            //if (ModelState.IsValid) return RedirectToAction("Index");
            //else return PartialView("_New", organisatie);
        }


        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (!id.HasValue) return RedirectToAction("Index");

            Organisatie organisatie = new Organisatie();
            organisatie = OrganisatieDA.GetOrganisatieById(id.Value);

            return PartialView("_Edit", organisatie);
        }

        [HttpPost]
        public ActionResult Edit(Organisatie organisatie)
        {
            OrganisatieDA.UpdateOrganisatie(organisatie);
            return RedirectToAction("Index");
        }


        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (!id.HasValue) return RedirectToAction("Index");

            Organisatie organisatie = new Organisatie();
            organisatie = OrganisatieDA.GetOrganisatieById(id.Value);

            return PartialView("_Details", organisatie);
        }


        [HttpGet]
        public ActionResult BekijkKassas(int? id)
        {
            if (!id.HasValue) return RedirectToAction("Index");

            List<OrganisatieKassa> organisatiekassas = new List<OrganisatieKassa>();
            organisatiekassas = OrganisatieKassaDA.GetOrganisatieKassas().Where(ok => ok.Organisatie.ID == id.Value).ToList();

            ViewBag.OrganisatieNaam = OrganisatieDA.GetOrganisatieById(id.Value).OrganisatieNaam;


            List<KassaIT> kassas = new List<KassaIT>();
            foreach(OrganisatieKassa ok in organisatiekassas)
            {
                kassas.Add(KassaDA.GetKassaById(ok.KassaIT.ID));
            }
            

            return PartialView("_BekijkKassas", kassas);
        }


        [HttpGet]
        public ActionResult DeleteOrganisatieKassa(int? id)
        {
            if (!id.HasValue) return RedirectToAction("Index");

            KassaIT kassa = KassaDA.GetKassaById(id.Value);
            ViewBag.KassaNaam = kassa.KassaNaam;

            List<OrganisatieKassa> organisatiekassas = OrganisatieKassaDA.GetOrganisatieKassas();
            OrganisatieKassa orgkassa = organisatiekassas.FirstOrDefault(ok => ok.KassaIT.ID == kassa.ID);

            if (orgkassa != null) ViewBag.SelectedOrganisatie = orgkassa.Organisatie.OrganisatieNaam;
            else ViewBag.SelectedOrganisatie = "geen organisatie";

            return View("DeleteOrganisatieKassa", kassa);
        }


        [HttpPost]
        public ActionResult DeleteOrganisatieKassa(KassaIT kassa)
        {
            OrganisatieKassaDA.DeleteOrganisatieKassa(kassa);

            return RedirectToAction("Index");
        }
    }
}

nmct.ssa.cashlessproject.webapp.it/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Cashlessproject</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="~/Scripts/jquery-2.1.1.mins.js"></script>


    <link rel="stylesheet" href="~/Content/datepicker.css" />
    <link rel="stylesheet" href="~/Content/jquery.dataTables.css" />
    <link rel="stylesheet" href="~/Content/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/Content/jquery.dataTables_themeroller.css" />

    <script type="text/javascript" src="~/Scripts/jquery.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.dataTables.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="~/Scripts/bootstrap-datepicker.js"></script>

    <script type="text/javascript" charset="utf-8">
        $(document).ready(function ()
        {
            $('.dtable').dataTable();
            $(".datepicker").datepicker();
        });
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Cashlessproject", "Index", "Organisatie", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
                    { 
                        <li>@Html.ActionLink("Organisaties", "Index", "Organisatie")</li>
                        <li>@Html.ActionLink("Kassa's", "Index", "Kassa")</li>
                        <li>@Html.ActionLink("Logging", "Index", "Errorlog")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Cashlessproject</p>
        </footer>
    </div>

    <script src='@Url.Content("~/Scripts/jquery.validate.js")' type='text/javascript'></script>
    <script src='@Url.Content("~/Scripts/jquery.validate.unobtrusive.js")' type='text/javascript'></script>

    @RenderSection("scripts", required: false)
</body>
</html>